### ISSUE TITLE
Manipulate height of headless tubing

### ISSUE THREAD

**Issue by JonathanDavidHarris** [AguaClara/filter-constrictions#2]
This will allow us to change the flow rate through the flow cell.
By Early March

**Comment by nataliemottl** [comment]
Do you have a target date to have each of these adjustments/tasks done? The tasks themselves look great, but it might be helpful to anticipate how long everything will take.

**Comment by JacquelineDokko** [comment]
- Added target dates for all tasks. 

- We adjusted the height of the outflow tubing which serves as headloss tubing to a position slightly higher than the major outlet tubing. This seems to have slowed down the flow in the flow cell to a velocity that is more accurate to that of the actual bed. The movement of individual particles can be seen better with this velocity. This will likely allow for more accurate measurements when using ImageJ for particle tracking since the particles will not appear smeared in each from of the videos. Will close issue after further testing with this tubing height to confirm success of these changes.

**Comment by JacquelineDokko** [comment]
Adjustable headloss tubing clamp has been installed on our work station. The height of the black pipe where we used to tape the tubing was measured to be 317cm high. The height of the white piping of the waste tube was measured to be 329cm from the floor. The tubing was secured onto the height-adjustable 80/20 via cable ties.
